### ISSUE TITLE
Write the content for the React page

### ISSUE THREAD

**Issue by jamie-taylor-rjj** [jamie-taylor-rjj/Recruitment-Glossary#48]
Be sure to read the readme for this repo with steps for getting started. It _should_  just be a case of using the current LTS of node and doing `npm install` and `npm run` to get the repo up and running.

## Summary

Write a series of paragraphs explaining .NET Maui in the same style as other pages in the application.

- The current .NET Maui page can be found at [https://recruitment-glossary.netlify.app/docs/npm/react/what-is-react/](https://recruitment-glossary.netlify.app/docs/npm/react/what-is-react/)
- An example page to follow would be the .NET page at [https://recruitment-glossary.netlify.app/docs/net/what-is-net/](https://recruitment-glossary.netlify.app/docs/net/what-is-net/)

Could also link back to the [npm/node page](https://recruitment-glossary.netlify.app/docs/npm/what-is-npm-and-nodejs/), as they are related

The important part to remember is that the page should not be the "be all, end all" of documentation. It is meant to be a gentle introduction to the topic, broken into fours separate parts:

- 10,000 ft Overview 
- Beginner information
- Intermediary Information 
- Advanced Information

This issue can cover just one of the above parts, and others will be created for the remaining parts of the page.

**Comment by RachitGarg-12** [comment]
Hey @jamie-taylor-rjj  please assign me this issue.

**Comment by jamie-taylor-rjj** [comment]
Assigned 👍
